// data.js

export const jobData = [
  // Original Internships from the first prompt
  {
    _id: "fiddle-internship-1",
    title: "Software Development - Internship",
    companyId: {
      name: "Fiddle",
      image: "https://placehold.co/128x128/F5F5F5/4B5563?text=Fiddle",
    },
    location: "Remote",
    level: "Internship",
    description: `As a Software Development Intern at Fiddle, you'll strengthen our engineering processes with robust evaluations, observability, and testing. You'll develop and maintain the core application across frontend, backend, and infrastructure, making foundational decisions that influence Fiddle's technical architecture and engineering culture. You'll also be responsible for shipping performant, pixel-perfect components to enhance user experience.`,
    stipend: "35,000",
    applyDate: "2025-09-25",
    requiredSkills: ["Backend development", "Frontend development", "React"],
    experience: "0-1 year",
    commonTopics: ["Engineering Processes", "Scalability", "Infrastructure", "User Experience (UX)"],
    applyLink: "https://internshala.com/internship/detail/software-development-internship-at-fiddle",
  },
  {
    _id: "linkedin-internship-1",
    title: "Software Engineering Intern",
    companyId: {
      name: "LinkedIn",
      image: "https://placehold.co/128x128/0A66C2/FFFFFF?text=LI",
    },
    location: "Bangalore",
    level: "Internship",
    description: `Join LinkedIn as a Software Engineering Intern. This is a summer internship opportunity for 2027 graduates. You'll get hands-on experience working on real-world projects in a professional environment, contributing to the development of our platform.`,
    stipend: "80,000",
    applyDate: "2025-08-27",
    requiredSkills: ["C++", "Java", "Python", "Algorithms", "Data Structures"],
    experience: "0-1 year",
    commonTopics: ["Object-Oriented Programming (OOP)", "System Design", "Backend Development", "Data Management"],
    applyLink: "https://www.linkedin.com/jobs/view/software-engineering-intern-3456789123",
  },
  {
    _id: "google-internship-1",
    title: "Web Solutions Engineer Intern, 2026",
    companyId: {
      name: "Google",
      image: "src/assets/logos/google.webp",
    },
    location: "Hyderabad",
    level: "Internship",
    description: `In this role, you will be designing, developing, and launching functionality to support growing business needs, which often involves building internal web applications. You will work on solutions that can scale to manage large datasets and improve platform architecture and resiliency. You will work closely with Engineering and Product teams to improve Google's products and internal tools.`,
    stipend: "80,000",
    applyDate: "2025-08-27",
    requiredSkills: ["C++", "Java", "Python", "Web Development", "API"],
    experience: "0-1 year",
    commonTopics: ["Web Solutions", "API Integration", "System Architecture", "Client Support"],
    applyLink: "https://careers.google.com/jobs/results/49887113110373076-web-solutions-engineer-intern-2026/",
  },
  {
    _id: "upstox-internship-1",
    title: "SDE Intern",
    companyId: {
      name: "Upstox",
      image: "https://placehold.co/128x128/50D890/FFFFFF?text=Upstox",
    },
    location: "Bengaluru/Mumbai",
    level: "Internship",
    description: `As an SDE Intern at Upstox, you'll be part of a team that builds and maintains our financial trading platform. You'll get hands-on experience with real-world development challenges and contribute to our mission of making financial markets accessible to everyone.`,
    stipend: "50,000",
    applyDate: "2025-08-27",
    requiredSkills: ["Backend development", "Frontend development", "Data Structures", "Algorithms"],
    experience: "0-1 year",
    commonTopics: ["System Design", "Scalability", "API Development", "Financial Technology"],
    applyLink: "https://upstox.com/careers/jobs/sde-internship-123456",
  },

  // Internships from the second prompt
  {
    _id: "microsoft-internship-1",
    title: "Explore Microsoft, Program",
    companyId: {
      name: "Microsoft",
      image: "https://placehold.co/128x128/0078D4/FFFFFF?text=MS",
    },
    location: "Hyderabad",
    level: "Internship",
    description: `The Explore Microsoft Program is a 12-week summer internship for first and second-year students. It provides a unique opportunity to experience both program management and software development roles. Interns will work on a real-world project, collaborating with experienced engineers and program managers to build innovative solutions.`,
    stipend: "75,000",
    applyDate: "2025-09-15",
    requiredSkills: ["C++", "C#", "Java", "Python", "Problem Solving"],
    experience: "0-1 year",
    commonTopics: ["Agile Development", "Cloud Computing", "Software Lifecycle", "Project Management"],
    applyLink: "https://careers.microsoft.com/us/en/job/1234567/Explore-Microsoft-Program",
  },
  {
    _id: "amazon-internship-1",
    title: "SDE Intern, Alexa AI",
    companyId: {
      name: "Amazon",
      image: "https://placehold.co/128x128/FF9900/FFFFFF?text=Amazon",
    },
    location: "Bangalore",
    level: "Internship",
    description: `As an SDE Intern at Amazon's Alexa AI team, you will be at the forefront of building the future of conversational AI. You will be responsible for designing and implementing software solutions, working on machine learning models, and ensuring the scalability and reliability of our systems. This role requires strong problem-solving skills and a passion for AI.`,
    stipend: "90,000",
    applyDate: "2025-09-01",
    requiredSkills: ["Python", "Machine Learning", "AWS", "Data Structures", "Algorithms"],
    experience: "0-1 year",
    commonTopics: ["Artificial Intelligence", "Natural Language Processing (NLP)", "Cloud Services", "Large-Scale Systems"],
    applyLink: "https://www.amazon.jobs/en/jobs/1234567/software-development-engineer-intern-alexa-ai",
  },
  {
    _id: "salesforce-internship-1",
    title: "Software Engineer Intern",
    companyId: {
      name: "Salesforce",
      image: "https://placehold.co/128x128/00A1E0/FFFFFF?text=SF",
    },
    location: "Hyderabad/Bangalore",
    level: "Internship",
    description: `Join Salesforce as a Software Engineer Intern and contribute to the world's leading CRM platform. You'll work on a variety of projects, from building new features to improving existing ones. This is a great opportunity to gain experience with enterprise-level software development, cloud technologies, and agile methodologies.`,
    stipend: "65,000",
    applyDate: "2025-08-30",
    requiredSkills: ["Java", "Apex", "JavaScript", "Cloud Computing", "Databases"],
    experience: "0-1 year",
    commonTopics: ["CRM", "Cloud-Based Solutions", "Scalability", "Agile Development", "Enterprise Software"],
    applyLink: "https://www.salesforce.com/company/careers/jobs/software-engineer-internship-1234567",
  },

  // Jobs from the third prompt
  {
    _id: "nvidia-internship-1",
    title: "Software Engineering Intern - OpenBMC",
    companyId: {
      name: "NVIDIA",
      image: "https://placehold.co/128x128/76B900/FFFFFF?text=NVIDIA",
    },
    location: "Taiwan, Taipei",
    level: "Internship",
    description: `As a Software Engineering Intern, you will be responsible for supporting the design and development of software solutions for Chip Resource Manager, Graphics, Video, 2D and 3D graphics under OpenGL and DirectX, ISP, System Management, and driver stacks for Windows and Linux OS. We are looking for interns who are passionate about working at the intersection of leading-edge graphics, multimedia, and operating system software.`,
    stipend: "Competitive",
    applyDate: "2025-09-25",
    requiredSkills: ["C", "C++", "Python", "Perl", "Operating Systems", "Algorithms", "Data Structures"],
    experience: "0-1 year",
    commonTopics: ["OpenBMC", "Graphics", "Operating Systems", "Drivers", "System Management", "Parallel Computing"],
    applyLink: "https://jobs.nvidia.com/job/JR1989739",
  },
  {
    _id: "groww-internship-1",
    title: "Web Team Intern",
    companyId: {
      name: "Groww",
      image: "https://placehold.co/128x128/179257/FFFFFF?text=Groww",
    },
    location: "Bangalore",
    level: "Internship",
    description: `Are you an ambitious intern with a passion for web development? Join the Groww Web Team and showcase your expertise in Next.js and React! We are looking for talented individuals to be a part of our innovative journey in the FinTech industry. At Groww, you'll play a pivotal role in empowering the next billion users with the magic of investing.`,
    stipend: "Not specified",
    applyDate: "2025-08-27",
    requiredSkills: ["Next.js", "React"],
    experience: "0-1 year",
    commonTopics: ["FinTech", "Web Development", "Frontend Development", "Investment"],
    applyLink: "https://docs.google.com/forms/d/e/1FAIpQLSeO5MFhRTl7RxR9b6F_xE_SJyOGRVf4eMeQx-ITGX5vrcDpPw/viewform",
  },
  {
    _id: "amazon-fulltime-1",
    title: "Software Development Engineer- I",
    companyId: {
      name: "Amazon",
      image: "https://placehold.co/128x128/FF9900/FFFFFF?text=Amazon",
    },
    location: "ADCI - Karnataka",
    level: "Full-Time",
    description: `At Amazon, we hire the best minds in technology to innovate and build on behalf of our customers. Our Software Development Engineers (SDEs) use technology to solve complex problems and get to see the impact of their work first-hand. We are looking for individuals who are passionate about creating new products, features, and services from scratch while managing ambiguity and the pace of a company where development cycles are measured in weeks, not years.`,
    stipend: "Not specified",
    applyDate: "2025-08-27",
    requiredSkills: ["Java", "C++", "Python", "Algorithms", "Data Structures"],
    experience: "0-1 year",
    commonTopics: ["Distributed Systems", "Cloud Computing", "Algorithms", "Problem Solving", "Agile"],
    applyLink: "https://www.amazon.jobs/en/jobs/2995991/software-development-engineer-i-adci-karnataka",
  },
  {
    _id: "giantlabs-internship-1",
    title: "Software Engineering - Internship",
    companyId: {
      name: "Giant Labs, Inc",
      image: "https://placehold.co/128x128/000000/FFFFFF?text=Giant+Labs",
    },
    location: "Work from home",
    level: "Internship",
    description: `As a Software Engineering intern, you will be responsible for feature development for our app, some web development or data engineering work related to our website, and other relevant works depending on business needs. We are looking for insanely cracked developers who truly enjoy engineering and are willing to work hard.`,
    stipend: "40,000",
    applyDate: "2025-09-21",
    requiredSkills: ["React", "React Native", "REST API"],
    experience: "0-1 year",
    commonTopics: ["Full Stack Development", "Mobile Development", "Data Engineering", "Web Development"],
    applyLink: "https://internshala.com/internship/detail/work-from-home-part-time-software-engineering-internship-at-giant-labs-inc1755842672/",
  },
  {
    _id: "wisemonk-internship-1",
    title: "Full Stack Development - Internship",
    companyId: {
      name: "Wisemonk TA",
      image: "https://placehold.co/128x128/6C63FF/FFFFFF?text=Wisemonk",
    },
    location: "Work from home",
    level: "Internship",
    description: `As a Full Stack Development intern, you will collaborate with the Engineering team on end-to-end feature development. You will design, build, test, and deploy full-stack web applications using either MERN (MongoDB, Express.js, React, Node.js) or PERN (PostgreSQL, Express.js, React, Node.js).`,
    stipend: "75,000 - 90,000",
    applyDate: "2025-09-19",
    requiredSkills: ["Express.js", "MongoDB", "Node.js", "React"],
    experience: "0-1 year",
    commonTopics: ["Full Stack Development", "MERN Stack", "PERN Stack", "AI Tools"],
    applyLink: "https://internshala.com/internship/detail/work-from-home-full-stack-development-internship-at-wisemonk-ta1755606546/",
  },
  {
    _id: "cisco-internship-1",
    title: "Software Engineer - (Summer Internship)",
    companyId: {
      name: "Cisco",
      image: "https://placehold.co/128x128/0466C2/FFFFFF?text=Cisco",
    },
    location: "Bangalore, India",
    level: "Internship",
    description: `As a Software Engineer intern, you will join a team that plays a crucial role in driving next-gen software innovations, including cloud, mobile, desktop, and security spaces. You'll build applications that make technology accessible to people on a variety of devices.`,
    stipend: "Not specified",
    applyDate: "2025-08-27",
    requiredSkills: ["Python", "C++", "Java", "Networking", "Operating Systems"],
    experience: "0-1 year",
    commonTopics: ["Cloud", "Networking Protocols", "Embedded Systems", "Security", "Software Development"],
    applyLink: "https://jobs.cisco.com/jobs/Login?projectId=1449112&source=KrishanKumarLinkedin&tags=2027summerinternship",
  },
  {
    _id: "mercor-contract-1",
    title: "Data Science Experts",
    companyId: {
      name: "Mercor",
      image: "https://placehold.co/128x128/000000/FFFFFF?text=Mercor",
    },
    location: "Remote",
    level: "Contract",
    description: `Mercor is hiring highly skilled Data Science experts to join a significant research collaboration with one of the world's leading AI labs. The role involves contributing to the development of advanced AI agents by creating evaluations for exploratory data analysis. You'll help train, test, and calibrate these AI systems.`,
    stipend: "$60-$110 per hour",
    applyDate: "2025-08-27",
    requiredSkills: ["Python", "Pandas", "Numpy", "Scikit-learn", "Statistical Modeling", "Machine Learning"],
    experience: "2+ years",
    commonTopics: ["Data Science", "AI", "Machine Learning", "Statistical Analysis", "Data Visualization"],
    applyLink: "https://work.mercor.com/jobs/list_AAABmKdTX17f_nKVFYlLZq7K?referralCode=be612532-6eb2-11ee-8bff-42010a400007",
  },
  {
    _id: "cartesia-fulltime-1",
    title: "Software Engineer – Cartesia India",
    companyId: {
      name: "Cartesia",
      image: "https://placehold.co/128x128/FF9900/FFFFFF?text=Cartesia",
    },
    location: "Bangalore Office",
    level: "Full-Time",
    description: `Cartesia is on a mission to shape the next generation of Artificial Intelligence—a future where interactive, multimodal intelligence can seamlessly operate across devices in real-time. As a Software Engineer, you will play a vital role in building scalable systems and enabling cutting-edge AI models to run efficiently across platforms.`,
    stipend: "70-90 LPA",
    applyDate: "2025-08-27",
    requiredSkills: ["Go", "Python", "Next.js", "Distributed Systems", "Scalability"],
    experience: "0-1 year",
    commonTopics: ["Artificial Intelligence", "Multimodal Intelligence", "Real-Time Systems", "Full Stack Development", "Machine Learning"],
    applyLink: "https://www.rgjobs.in/job/1287/software-engineer-cartesia-india-bangalore-office",
  },

  // BlackRock Internships from the fourth prompt
  {
    _id: "blackrock-apac-internship-1",
    title: "2026 Summer Internship Program - APAC",
    companyId: {
      name: "BlackRock",
      image: "https://placehold.co/128x128/000000/FFFFFF?text=BlackRock",
    },
    location: "Hong Kong, Japan, Singapore",
    level: "Internship",
    description: `The Summer Internship Program is for candidates in their penultimate year of a bachelor’s or master’s degree, graduating between September 2026 and August 2027. This program is designed to provide students with a challenging, meaningful and supportive internship experience that replicates, as closely as possible, the experience of being a full-time BlackRock Analyst.`,
    stipend: "Not specified",
    applyDate: "2025-09-14",
    requiredSkills: [],
    experience: "0-1 year",
    commonTopics: ["Investment", "Asset Management", "Financial Services", "Networking"],
    applyLink: "https://blackrock.tal.net/vx/lang-en-GB/mobile-0/brand-3/user-2203350/xf-c1647855dd7b/candidate/so/pm/1/pl/1/opp/9605-2026-Summer-Internship-Program-APAC/en-GB",
  },
  {
    _id: "blackrock-amers-internship-1",
    title: "2026 Summer Internship Program - AMERS",
    companyId: {
      name: "BlackRock",
      image: "https://placehold.co/128x128/000000/FFFFFF?text=BlackRock",
    },
    location: "United States, Canada",
    level: "Internship",
    description: `Our Summer Internship Program is a nine-week internship taking place June through August. This program is designed to provide students with a challenging, meaningful and supportive internship experience that replicates, as closely as possible, the experience of being a full-time BlackRock Analyst.`,
    stipend: "Varies by location (e.g., $36.05 - $56.49 USD/hour)",
    applyDate: "2025-10-24",
    requiredSkills: [],
    experience: "0-1 year",
    commonTopics: ["Finance", "Investment", "Corporate Strategy", "Technology"],
    applyLink: "https://blackrock.tal.net/vx/lang-en-GB/mobile-0/brand-3/user-2203350/xf-c1647855dd7b/candidate/so/pm/1/pl/1/opp/9601-2026-Summer-Internship-Program-AMERS/en-GB",
  },
];